name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_OPTIONAL: 'false'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'


      - name: Clean install artifacts and lockfiles
        run: |
          rm -rf node_modules package-lock.json pnpm-lock.yaml yarn.lock || true

      - name: Install dependencies (npm, no optional deps)
        run: npm install --no-optional

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
